import { Inter } from 'next/font/google';
import { ThemeProvider } from '@/components/theme-provider';
import './globals.css';
import QueryProvider from '@/components/query-provider';
import Navbar from '@/components/Navbar';
import MobileNavbar from '@/components/MobileNavbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  manifest: '/manifest.json',
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <QueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex flex-col items-center min-h-screen">
              <header className="text-center py-5 text-xl font-bold">
                🥦 Calo<span className="text-orange-500">bro.</span>
              </header>
              <main className="max-w-6xl w-full px-4 py-2 mx-auto space-y-10">
                {/* <Navbar /> */}
                {children}
              </main>
              <MobileNavbar />
            </div>
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
